name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Puxar o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Compilar os arquivos Java
      - name: Compile Java sources
        run: |
          find . -name "*.java" > sources.txt
          javac @sources.txt

      # 4️⃣ Criar o .jar executável
      - name: Package into JAR
        run: |
          jar cfe Main.jar Main $(find . -name "*.class")

      # 5️⃣ Testar a aplicação (opcional)
      - name: Run Application
        run: java -jar Main.jar

      # 6️⃣ Build da imagem Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/java-app:latest .

      # 7️⃣ Login no Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8️⃣ Push da imagem para Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/java-app:latest
