name: Java CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Compilar código Java
      run: |
        mkdir -p out
        javac -d out src/Model/*.java src/Service/*.java Carro/Model/*.java Carro/Service/*.java Concessionaria/Model/*.java Concessionaria/Service/*.java Main.java

    - name: Rodar aplicação
      run: java -cp out Main
