name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Compilar todas as classes respeitando pacotes
      - name: Compile Java sources
        run: |
          mkdir -p out
          find . -name "*.java" > sources.txt
          javac -d out @sources.txt

      # 4️⃣ Criar o JAR executável
      - name: Package into JAR
        run: |
          cd out
          jar cfe ../Main.jar Main $(find . -name "*.class")
          cd ..

      
