name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Compilar arquivos
        run: |
          mkdir -p build
          javac -d build $(find src -name "*.java")

      - name: Criar arquivo JAR
        run: jar cfe build/app.jar com.exemplo.Main -C build .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p ~/app
            mv app-jar/app.jar ~/app/app.jar
            nohup java -jar ~/app/app.jar > ~/app/log.txt 2>&1 &
            echo "Deploy concluído com sucesso!"

