name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Compilar todas as classes respeitando pacotes
      - name: Compile Java sources
        run: |
          mkdir -p out
          find . -name "*.java" > sources.txt
          javac -d out @sources.txt

      # 4️⃣ Criar o JAR executável
      - name: Package into JAR
        run: |
          cd out
          jar cfe ../Main.jar Main $(find . -name "*.class")
          cd ..

      # 5️⃣ Testar o JAR localmente
      - name: Run JAR
        run: java -cp Main.jar Main

     
      # 9️⃣ Deploy no servidor via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /caminho/do/projeto/no/servidor
            # Atualizar JAR
            cp /tmp/Main.jar ./Main.jar
            # Parar app antigo
            pkill -f Main.jar || true
            # Rodar novo JAR em background
            nohup java -cp Main.jar Main > app.log 2>&1 &
